# Generated by Django 3.2 on 2022-01-18 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.TextField()),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('post_pic', models.FileField(blank=True, null=True, upload_to='images')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL)),
                ('liked_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('comment_pic', models.FileField(blank=True, null=True, upload_to='images')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('embedded_comment', models.BooleanField(default=False)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenting_username', to=settings.AUTH_USER_MODEL)),
                ('post_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_creator_username', to=settings.AUTH_USER_MODEL)),
                ('target_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attach_to', to='my_brew_posts.userpost')),
            ],
        ),
    ]
