# Generated by Django 3.2 on 2022-01-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
