# Generated by Django 3.2 on 2022-01-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_posts', '0002_alter_userpost_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='post_pic',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
