# Generated by Django 3.2 on 2022-01-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_posts', '0004_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='comment_pic',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
