# Generated by Django 3.2 on 2022-01-11 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_brew_posts', '0005_postcomment_comment_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='post_creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_creator_username', to='my_brew_app.mybrewuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenting_username', to=settings.AUTH_USER_MODEL),
        ),
    ]
