# Generated by Django 3.2 on 2022-01-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_posts', '0006_auto_20220111_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='id',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='userpost',
            old_name='id',
            new_name='post_id',
        ),
    ]
