# Generated by Django 3.2 on 2022-01-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_posts', '0007_auto_20220115_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='post_id',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
