# Generated by Django 3.2 on 2022-01-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_posts', '0008_auto_20220115_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
