# Generated by Django 3.2 on 2022-01-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBrewBrewery',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('brewery_name', models.CharField(max_length=180, null=True)),
                ('brewery_logo', models.FileField(blank=True, null=True, upload_to='brewery_images/')),
                ('brewery_hero_image', models.FileField(blank=True, null=True, upload_to='brewery_images/')),
                ('brewery_bio', models.TextField(null=True)),
                ('brewery_address', models.CharField(max_length=180, null=True)),
                ('brewery_city', models.CharField(max_length=180, null=True)),
                ('brewery_state', models.CharField(max_length=180, null=True)),
                ('brewery_zip', models.CharField(max_length=180, null=True)),
                ('brewery_phone', models.CharField(max_length=10, null=True)),
                ('brewery_website', models.URLField(blank=True, max_length=350, null=True)),
                ('brewery_rating_total', models.IntegerField(default=0)),
                ('brewery_num_votes', models.IntegerField(default=0)),
                ('brewery_rating', models.FloatField(default=0, max_length=12)),
            ],
        ),
    ]
