# Generated by Django 3.2 on 2022-01-25 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_brew_brewery', '0002_alter_mybrewbrewery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybrewbrewery',
            name='brewery_moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brewery_moderator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mybrewbrewery',
            name='brewery_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='brewery_images/'),
        ),
        migrations.AlterField(
            model_name='mybrewbrewery',
            name='brewery_logo',
            field=models.ImageField(blank=True, null=True, upload_to='brewery_images/'),
        ),
    ]
