# Generated by Django 3.2 on 2022-01-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybrewuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
