# Generated by Django 3.2 on 2021-04-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0002_alter_mybrewuser_favorite_beer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybrewuser',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
