# Generated by Django 3.2 on 2021-04-23 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0003_alter_mybrewuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybrewuser',
            name='profile_pic',
        ),
    ]
