# Generated by Django 3.2 on 2021-04-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0004_remove_mybrewuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybrewuser',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
