# Generated by Django 3.2 on 2021-04-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0005_mybrewuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybrewuser',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='mybrewuser',
            name='favorite_beer',
            field=models.CharField(blank=True, default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mybrewuser',
            name='state',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
