# Generated by Django 3.2 on 2021-04-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0006_auto_20210423_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breweries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('brewer_type', models.CharField(max_length=180)),
                ('street', models.CharField(max_length=180)),
                ('state', models.CharField(max_length=180)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=180)),
                ('longitude', models.CharField(max_length=180)),
                ('latitude', models.CharField(max_length=180)),
                ('phone', models.CharField(max_length=11)),
                ('website_url', models.URLField(max_length=350)),
            ],
        ),
        migrations.AddField(
            model_name='mybrewuser',
            name='favorites',
            field=models.ManyToManyField(to='my_brew_app.Breweries'),
        ),
    ]
