# Generated by Django 3.2 on 2021-04-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0007_auto_20210424_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybrewuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='my_brew_app.Breweries'),
        ),
    ]
