# Generated by Django 3.2 on 2021-04-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0008_alter_mybrewuser_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breweries',
            name='brewer_type',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='breweries',
            name='country',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='breweries',
            name='latitude',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='breweries',
            name='longitude',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='breweries',
            name='name',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='breweries',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='breweries',
            name='postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='breweries',
            name='state',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='breweries',
            name='street',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='breweries',
            name='website_url',
            field=models.URLField(max_length=350, null=True),
        ),
    ]
