# Generated by Django 3.2 on 2021-04-26 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0009_auto_20210425_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='breweries',
            name='rating',
            field=models.FloatField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name='breweries',
            name='rating_list',
            field=models.CharField(default=5, max_length=6, validators=[django.core.validators.int_list_validator]),
        ),
    ]
