# Generated by Django 3.2 on 2021-04-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0011_auto_20210426_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breweries',
            name='num_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='breweries',
            name='rating_total',
            field=models.IntegerField(default=0),
        ),
    ]
