# Generated by Django 3.2 on 2021-04-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0012_auto_20210426_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='breweries',
            name='city',
            field=models.CharField(max_length=180, null=True),
        ),
    ]
