# Generated by Django 3.2 on 2021-04-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0013_breweries_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breweries',
            name='latitude',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='breweries',
            name='longitude',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
