# Generated by Django 3.2 on 2021-04-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0014_auto_20210428_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breweries',
            name='website_url',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
    ]
