# Generated by Django 3.2 on 2021-05-22 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0016_brewerycomment_breweryimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybrewuser',
            name='brewery_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_operator', to='my_brew_app.breweries'),
        ),
        migrations.AddField(
            model_name='mybrewuser',
            name='brewery_owner',
            field=models.BooleanField(default=False),
        ),
    ]
