# Generated by Django 3.2 on 2021-10-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0018_rename_brewery_operator_mybrewuser_my_brewery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breweryimages',
            name='brewery',
        ),
        migrations.RemoveField(
            model_name='mybrewuser',
            name='brewery_owner',
        ),
        migrations.RemoveField(
            model_name='mybrewuser',
            name='my_brewery',
        ),
        migrations.DeleteModel(
            name='BreweryComment',
        ),
        migrations.DeleteModel(
            name='BreweryImages',
        ),
    ]
