# Generated by Django 3.2 on 2021-12-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_brewery', '0001_initial'),
        ('my_brew_app', '0019_auto_20211001_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Breweries',
        ),
        migrations.AlterField(
            model_name='mybrewuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='my_brew_brewery.MyBrewBrewery'),
        ),
        migrations.AlterField(
            model_name='mybrewuser',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
