# Generated by Django 3.2 on 2021-12-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0020_auto_20211211_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.CharField(max_length=16)),
                ('user', models.CharField(max_length=150)),
            ],
        ),
    ]
