# Generated by Django 3.2 on 2021-12-21 03:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0021_temporaryurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mybrewuser',
            old_name='favorites',
            new_name='followed_brewery',
        ),
        migrations.AddField(
            model_name='mybrewuser',
            name='followed_user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
