# Generated by Django 3.2 on 2021-12-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0023_auto_20211222_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserUpdates',
            new_name='UserPosts',
        ),
    ]
