# Generated by Django 3.2 on 2021-12-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0024_rename_userupdates_userposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
