# Generated by Django 3.2 on 2021-12-22 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0027_alter_userposts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
