# Generated by Django 3.2 on 2021-12-22 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0029_rename_update_userposts_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposts',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='userposts',
            name='liked_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
