# Generated by Django 3.2 on 2022-01-07 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0030_auto_20211222_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPosts',
        ),
    ]
