# Generated by Django 3.2 on 2022-01-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0031_delete_userposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybrewuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
