# Generated by Django 3.2 on 2022-01-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_app', '0032_alter_mybrewuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybrewuser',
            name='brewery_owner',
            field=models.BooleanField(default=False),
        ),
    ]
