# Generated by Django 3.2 on 2022-01-08 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_brew_posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_brew_posts.userpost')),
            ],
        ),
    ]
