# Generated by Django 3.2 on 2022-01-08 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_brew_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostnotification',
            name='user_mentioned',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mentioned', to='my_brew_app.mybrewuser'),
            preserve_default=False,
        ),
    ]
