# Generated by Django 3.2 on 2022-01-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_notifications', '0002_userpostnotification_user_mentioned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostnotification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
