# Generated by Django 3.2 on 2022-01-19 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_brew_posts', '0002_auto_20220118_2352'),
        ('my_brew_notifications', '0003_userpostnotification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpostnotification',
            name='notification_type',
        ),
        migrations.AlterField(
            model_name='userpostnotification',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpostnotification',
            name='target_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_target', to='my_brew_posts.userpost'),
        ),
        migrations.AlterField(
            model_name='userpostnotification',
            name='user_mentioned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentioned_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserCommentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('target_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_target', to='my_brew_posts.postcomment')),
                ('user_mentioned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentioned_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
