# Generated by Django 3.2 on 2022-01-19 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_notifications', '0004_auto_20220119_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommentnotification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userpostnotification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
