# Generated by Django 3.2 on 2022-01-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_brew_notifications', '0005_auto_20220119_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercommentnotification',
            old_name='comment_by',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='usercommentnotification',
            old_name='target_comment',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='userpostnotification',
            old_name='posted_by',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='userpostnotification',
            old_name='target_post',
            new_name='target',
        ),
    ]
